import type{Event}from"./types";
export const categories=["Music","Workshops","Comedy","Art","Food","Conversations"];
export const events:Event[]=[
{id:"river",slug:"the-river-room",title:"The river room",category:"Music",status:"UPCOMING",featured:true,date:"2026-09-18T20:00:00+05:00",doors:"7:30 pm",start:"8:00 pm",duration:"2 hours",venue:"Bazm, Hyderabad",summary:"An intimate evening of original sound, improvisation and stories between songs.",description:"A close-room listening session shaped around acoustic performance and conversation. Fictional demonstration programming for the Bazm booking experience.",image:"/assets/venue-wall.png",host:"Bazm programme team",age:"16+",language:"Urdu / English",accessibility:"Step-free entry and assisted seating available on request.",tiers:[{id:"river-general",name:"General admission",price:80000,capacity:70,sold:42,limit:4},{id:"river-supporter",name:"Supporter seat",price:120000,capacity:15,sold:9,limit:2}]},
{id:"clay",slug:"clay-and-quiet",title:"Clay & quiet",category:"Workshops",status:"UPCOMING",date:"2026-09-19T17:00:00+05:00",doors:"4:45 pm",start:"5:00 pm",duration:"2.5 hours",venue:"Bazm workshop room",summary:"A guided introduction to hand-building with clay in a calm, shared studio.",description:"Make a small functional object while learning the foundations of hand-building. Materials included. Demo event only.",image:"/assets/gallery.png",host:"Guest maker · demo listing",age:"14+",language:"Urdu / Sindhi / English",accessibility:"Seated workshop with step-free entry.",tiers:[{id:"clay-seat",name:"Workshop seat",price:150000,capacity:18,sold:12,limit:2}]},
{id:"stories",slug:"stories-after-sunset",title:"Stories after sunset",category:"Conversations",status:"UPCOMING",date:"2026-09-24T19:30:00+05:00",doors:"7:00 pm",start:"7:30 pm",duration:"90 minutes",venue:"Bazm main room",summary:"Writers and listeners gather around new work, local memory and a good question.",description:"An informal reading circle followed by a hosted conversation. Demo event only.",image:"/assets/grid-two.png",host:"Bazm conversations",age:"All ages",language:"Urdu / Sindhi",accessibility:"Quiet seating area available on request.",tiers:[{id:"stories-entry",name:"Entry",price:50000,capacity:55,sold:21,limit:5}]},
{id:"comedy",slug:"small-room-comedy",title:"Small room comedy",category:"Comedy",status:"SOLD_OUT",date:"2026-09-26T20:30:00+05:00",doors:"8:00 pm",start:"8:30 pm",duration:"90 minutes",venue:"Bazm main room",summary:"New material, close tables and a room that listens.",description:"A fictional listing demonstrating sold-out states.",image:"/assets/posters.png",host:"Demo line-up",age:"18+",language:"Urdu / English",accessibility:"Step-free entry available.",tiers:[{id:"comedy-general",name:"General admission",price:90000,capacity:60,sold:60,limit:4}]},
{id:"table",slug:"the-shared-table",title:"The shared table",category:"Food",status:"POSTPONED",date:"2026-10-02T19:00:00+05:00",doors:"6:45 pm",start:"7:00 pm",duration:"2 hours",venue:"Bazm café",summary:"A seasonal menu and stories carried by familiar recipes.",description:"A fictional food gathering. New date to be announced.",image:"/assets/grid-one.png",host:"Bazm café",age:"All ages",language:"Urdu / English",accessibility:"Share dietary access requirements before attending.",tiers:[{id:"table-place",name:"Table place",price:180000,capacity:28,sold:8,limit:4}]},
{id:"print",slug:"print-and-pattern",title:"Print & pattern",category:"Art",status:"COMPLETED",date:"2026-07-12T16:00:00+05:00",doors:"3:45 pm",start:"4:00 pm",duration:"3 hours",venue:"Bazm workshop room",summary:"A practical afternoon exploring repeat, block and ink.",description:"A completed fictional event retained to demonstrate programme states.",image:"/assets/gallery.png",host:"Demo workshop host",age:"12+",language:"Urdu / English",accessibility:"Seated and standing work surfaces available.",tiers:[{id:"print-seat",name:"Workshop seat",price:140000,capacity:20,sold:18,limit:2}]}
];
export const transfer={method:"Bank transfer / mobile wallet",accountTitle:"BAZM — DEMO ACCOUNT",provider:"Organiser details required",masked:"•••• •••• •••• 2046",minutes:45,maxBytes:5*1024*1024};export const getEvent=(slug:string)=>events.find(e=>e.slug===slug);export const getEventId=(id:string)=>events.find(e=>e.id===id);
