import { z } from "zod";
import { listCategories, slugAvailable, type ManagedEvent, type ManagedEventInput } from "./events.ts";

export const slugSchema = z.string().trim().min(2).max(100).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, "Use lowercase letters, numbers and single hyphens only");
export const categorySchema = z.object({ name: z.string().trim().min(2).max(60), slug: slugSchema });
const eventSchema = z.object({
  title:z.string().trim().min(2).max(140),slug:slugSchema,shortSummary:z.string().trim().min(10).max(260),fullDescription:z.string().trim().min(20).max(10000),categoryId:z.string().uuid().or(z.string().regex(/^cat-/)),hostArtist:z.string().trim().min(2).max(180),eventDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),doorsOpenTime:z.string().regex(/^\d{2}:\d{2}$/),startTime:z.string().regex(/^\d{2}:\d{2}$/),endTime:z.string().regex(/^\d{2}:\d{2}$/),venue:z.string().trim().min(2).max(240),ageGuidance:z.string().trim().min(1).max(100),languages:z.string().trim().min(2).max(180),accessibilityInformation:z.string().trim().min(2).max(2000),specialInstructions:z.string().trim().max(2000),featured:z.boolean(),seoTitle:z.string().trim().max(70),seoDescription:z.string().trim().max(170),coverImageKey:z.string().optional()
}).superRefine((input,context)=>{if(input.endTime<=input.startTime)context.addIssue({code:"custom",path:["endTime"],message:"End time must be after the start time"});if(input.doorsOpenTime>input.startTime)context.addIssue({code:"custom",path:["doorsOpenTime"],message:"Doors must open at or before the start time"})});

export function eventInputFromForm(form:FormData,coverImageKey?:string):ManagedEventInput{
  return eventSchema.parse({title:form.get("title"),slug:form.get("slug"),shortSummary:form.get("shortSummary"),fullDescription:form.get("fullDescription"),categoryId:form.get("categoryId"),hostArtist:form.get("hostArtist"),eventDate:form.get("eventDate"),doorsOpenTime:form.get("doorsOpenTime"),startTime:form.get("startTime"),endTime:form.get("endTime"),venue:form.get("venue"),ageGuidance:form.get("ageGuidance"),languages:form.get("languages"),accessibilityInformation:form.get("accessibilityInformation"),specialInstructions:form.get("specialInstructions")||"",featured:form.get("featured")==="true",seoTitle:form.get("seoTitle")||"",seoDescription:form.get("seoDescription")||"",coverImageKey});
}
export async function validateEventReferences(input:ManagedEventInput,excludeId?:string){if(!(await slugAvailable(input.slug,excludeId)))throw Error("This URL slug is already in use");const category=(await listCategories()).find(item=>item.id===input.categoryId);if(!category)throw Error("Choose a valid category");if(!category.enabled&&!excludeId)throw Error("Choose an enabled category")}
export function validateForPublication(event:ManagedEvent){const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Karachi",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());if(event.eventDate<=today)throw Error("Published events must have a future date in Asia/Karachi");if(!event.title||!event.slug||!event.categoryId)throw Error("Title, unique slug and category are required before publication")}
export function validationMessage(error:unknown){if(error instanceof z.ZodError)return error.issues.map(issue=>`${issue.path.join(".")}: ${issue.message}`).join(" · ");return error instanceof Error?error.message:"Unable to save the event"}
