import { randomUUID } from "node:crypto";
import type { PoolClient } from "pg";
import { one, query, transaction } from "./database.ts";
import type { Event as PublicEvent, EventStatus as PublicEventStatus } from "./types.ts";
import { publicTicketSelection } from "./ticketing.ts";

export type ManagedEventStatus = "DRAFT" | "PUBLISHED" | "POSTPONED" | "CANCELLED" | "COMPLETED" | "ARCHIVED";
export type Category = { id: string; name: string; slug: string; sortOrder: number; enabled: boolean; eventCount: number; createdAt: string; updatedAt: string };
export type ManagedEvent = {
  id: string; title: string; slug: string; shortSummary: string; fullDescription: string; categoryId: string; categoryName: string;
  coverImageKey?: string; hostArtist: string; eventDate: string; doorsOpenTime: string; startTime: string; endTime: string;
  venue: string; ageGuidance: string; languages: string; accessibilityInformation: string; specialInstructions: string;
  featured: boolean; seoTitle: string; seoDescription: string; status: ManagedEventStatus; statusReason?: string;
  publishedAt?: string; createdAt: string; updatedAt: string;
};
export type ManagedEventInput = Omit<ManagedEvent,"id"|"categoryName"|"status"|"statusReason"|"publishedAt"|"createdAt"|"updatedAt">;

type CategoryRow = { id:string;name:string;slug:string;sort_order:number;enabled:boolean;event_count:string|number;created_at:string;updated_at:string };
type EventRow = { id:string;title:string;slug:string;short_summary:string;full_description:string;category_id:string;category_name:string;cover_image_key:string|null;host_artist:string;event_date:string;doors_open_time:string;start_time:string;end_time:string;venue:string;age_guidance:string;languages:string;accessibility_information:string;special_instructions:string;featured:boolean;seo_title:string;seo_description:string;status:ManagedEventStatus;status_reason:string|null;published_at:string|null;created_at:string;updated_at:string };
const categoryFromRow=(row:CategoryRow):Category=>({id:row.id,name:row.name,slug:row.slug,sortOrder:Number(row.sort_order),enabled:Boolean(row.enabled),eventCount:Number(row.event_count),createdAt:row.created_at,updatedAt:row.updated_at});
const eventFromRow=(row:EventRow):ManagedEvent=>({id:row.id,title:row.title,slug:row.slug,shortSummary:row.short_summary,fullDescription:row.full_description,categoryId:row.category_id,categoryName:row.category_name,coverImageKey:row.cover_image_key??undefined,hostArtist:row.host_artist,eventDate:row.event_date,doorsOpenTime:row.doors_open_time,startTime:row.start_time,endTime:row.end_time,venue:row.venue,ageGuidance:row.age_guidance,languages:row.languages,accessibilityInformation:row.accessibility_information,specialInstructions:row.special_instructions,featured:Boolean(row.featured),seoTitle:row.seo_title,seoDescription:row.seo_description,status:row.status,statusReason:row.status_reason??undefined,publishedAt:row.published_at??undefined,createdAt:row.created_at,updatedAt:row.updated_at});
const eventSelect=`SELECT e.*,c.name category_name FROM admin_events e JOIN event_categories c ON c.id=e.category_id`;

export async function listCategories(includeDisabled=true){const where=includeDisabled?"":"WHERE c.enabled=true";return(await query<CategoryRow>(`SELECT c.*,COUNT(e.id) event_count FROM event_categories c LEFT JOIN admin_events e ON e.category_id=c.id ${where} GROUP BY c.id ORDER BY c.sort_order,c.name`)).rows.map(categoryFromRow)}
export async function createCategory(input:{name:string;slug:string},actorId:string){const exists=await one("SELECT 1 FROM event_categories WHERE lower(name)=lower($1) OR lower(slug)=lower($2) LIMIT 1",[input.name,input.slug]);if(exists)throw Error("Category name or slug is already in use");const sort=Number((await one<{ value:string }>("SELECT COALESCE(MAX(sort_order),0)+10 value FROM event_categories"))?.value??10),id=randomUUID();const now=new Date().toISOString();await query("INSERT INTO event_categories(id,name,slug,sort_order,enabled,created_at,updated_at) VALUES($1,$2,$3,$4,true,$5,$6)",[id,input.name,input.slug,sort,now,now]);return(await listCategories()).find(item=>item.id===id)!}
export async function updateCategory(id:string,input:{name:string;slug:string;enabled:boolean},actorId:string){const exists=await one("SELECT 1 FROM event_categories WHERE id<>$1 AND (lower(name)=lower($2) OR lower(slug)=lower($3)) LIMIT 1",[id,input.name,input.slug]);if(exists)throw Error("Category name or slug is already in use");const result=await query("UPDATE event_categories SET name=$1,slug=$2,enabled=$3,updated_at=$4 WHERE id=$5",[input.name,input.slug,input.enabled,new Date().toISOString(),id]);if(!result.rowCount)throw Error("Category not found");return(await listCategories()).find(item=>item.id===id)!}
export async function reorderCategories(ids:string[]){await transaction(async client=>{const now=new Date().toISOString();await Promise.all(ids.map((id,index)=>query("UPDATE event_categories SET sort_order=$1,updated_at=$2 WHERE id=$3",[(index+1)*10,now,id],client)))});return listCategories()}
export async function deleteCategory(id:string){const count=Number((await one<{ count:string }>("SELECT COUNT(*) count FROM admin_events WHERE category_id=$1",[id]))?.count??0);if(count>0)throw Error("This category is assigned to events and cannot be deleted");const result=await query("DELETE FROM event_categories WHERE id=$1",[id]);if(!result.rowCount)throw Error("Category not found")}

export async function listManagedEvents(){return(await query<EventRow>(`${eventSelect} ORDER BY e.updated_at DESC`)).rows.map(eventFromRow)}
export async function getManagedEvent(id:string){const row=await one<EventRow>(`${eventSelect} WHERE e.id=$1 LIMIT 1`,[id]);return row?eventFromRow(row):undefined}
export async function slugAvailable(slug:string,excludeId?:string){const row=await one("SELECT id FROM admin_events WHERE lower(slug)=lower($1) AND ($2::text IS NULL OR id<>$2) LIMIT 1",[slug,excludeId??null]);return!row}
export async function createManagedEvent(input:ManagedEventInput,actorId:string){const id=randomUUID(),now=new Date().toISOString();await query(`INSERT INTO admin_events(id,title,slug,short_summary,full_description,category_id,cover_image_key,host_artist,event_date,doors_open_time,start_time,end_time,venue,age_guidance,languages,accessibility_information,special_instructions,featured,seo_title,seo_description,status,created_by,updated_by,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,'DRAFT',$21,$22,$23,$24)`,[id,input.title,input.slug,input.shortSummary,input.fullDescription,input.categoryId,input.coverImageKey??null,input.hostArtist,input.eventDate,input.doorsOpenTime,input.startTime,input.endTime,input.venue,input.ageGuidance,input.languages,input.accessibilityInformation,input.specialInstructions,input.featured,input.seoTitle,input.seoDescription,actorId,actorId,now,now]);return(await getManagedEvent(id))!}
export async function updateManagedEvent(id:string,input:ManagedEventInput,actorId:string){const result=await query(`UPDATE admin_events SET title=$1,slug=$2,short_summary=$3,full_description=$4,category_id=$5,cover_image_key=$6,host_artist=$7,event_date=$8,doors_open_time=$9,start_time=$10,end_time=$11,venue=$12,age_guidance=$13,languages=$14,accessibility_information=$15,special_instructions=$16,featured=$17,seo_title=$18,seo_description=$19,updated_by=$20,updated_at=$21 WHERE id=$22`,[input.title,input.slug,input.shortSummary,input.fullDescription,input.categoryId,input.coverImageKey??null,input.hostArtist,input.eventDate,input.doorsOpenTime,input.startTime,input.endTime,input.venue,input.ageGuidance,input.languages,input.accessibilityInformation,input.specialInstructions,input.featured,input.seoTitle,input.seoDescription,actorId,new Date().toISOString(),id]);if(!result.rowCount)throw Error("Event not found");return(await getManagedEvent(id))!}
export async function changeEventStatus(id:string,status:ManagedEventStatus,actorId:string,reason?:string){const event=await getManagedEvent(id);if(!event)throw Error("Event not found");if(["POSTPONED","CANCELLED"].includes(status)&&(!reason||reason.trim().length<5))throw Error("A reason of at least 5 characters is required");const now=new Date().toISOString(),publishedAt=status==="PUBLISHED"?(event.publishedAt??now):status==="DRAFT"?null:event.publishedAt??null;await transaction(async client=>{await query("UPDATE admin_events SET status=$1,status_reason=$2,published_at=$3,updated_by=$4,updated_at=$5 WHERE id=$6",[status,reason?.trim()||null,publishedAt,actorId,now,id],client);await query("INSERT INTO event_status_history(id,event_id,from_status,to_status,reason,changed_by,changed_at) VALUES($1,$2,$3,$4,$5,$6,$7)",[randomUUID(),id,event.status,status,reason?.trim()||null,actorId,now],client)});return(await getManagedEvent(id))!}
export async function duplicateManagedEvent(id:string,actorId:string){const source=await getManagedEvent(id);if(!source)throw Error("Event not found");let slug=`${source.slug}-copy`,counter=2;while(!(await slugAvailable(slug)))slug=`${source.slug}-copy-${counter++}`;return createManagedEvent({...source,slug,title:`${source.title} (Copy)`,featured:false,coverImageKey:source.coverImageKey},actorId)}
export async function getPublishedEvents(){return(await query<EventRow>(`${eventSelect} WHERE e.published_at IS NOT NULL AND e.status IN ('PUBLISHED','POSTPONED','CANCELLED','COMPLETED') ORDER BY e.featured DESC,e.event_date,e.start_time`)).rows.map(eventFromRow)}
export async function getPublishedEventBySlug(slug:string){const row=await one<EventRow>(`${eventSelect} WHERE lower(e.slug)=lower($1) AND e.published_at IS NOT NULL AND e.status IN ('PUBLISHED','POSTPONED','CANCELLED','COMPLETED') LIMIT 1`,[slug]);return row?eventFromRow(row):undefined}
export async function eventUsingImage(key:string){const row=await one<{id:string;status:ManagedEventStatus;published_at:string|null}>("SELECT id,status,published_at FROM admin_events WHERE cover_image_key=$1 LIMIT 1",[key]);return row?{id:row.id,isPublic:Boolean(row.published_at)&&!["DRAFT","ARCHIVED"].includes(row.status)}:undefined}
export async function toPublicEvent(event:ManagedEvent):Promise<PublicEvent>{const status:PublicEventStatus=["PUBLISHED","DRAFT","ARCHIVED"].includes(event.status)?"UPCOMING":event.status as PublicEventStatus,selection=await publicTicketSelection(event.id);return{id:event.id,slug:event.slug,title:event.title,category:event.categoryName,status,date:`${event.eventDate}T${event.startTime}:00+05:00`,doors:event.doorsOpenTime,start:event.startTime,duration:`${event.startTime}–${event.endTime}`,venue:event.venue,summary:event.shortSummary,description:event.fullDescription,image:event.coverImageKey?`/api/event-images/${event.coverImageKey}`:"/assets/gallery.png",host:event.hostArtist,age:event.ageGuidance,language:event.languages,accessibility:event.accessibilityInformation,featured:event.featured,ticketingState:selection.state,tiers:selection.tiers.map(tier=>({id:tier.id,name:tier.name,description:tier.description,price:tier.price,capacity:tier.capacity,sold:tier.confirmed,reserved:tier.reserved,available:tier.remaining,limit:Math.min(tier.maxPerOrder,tier.remaining)}))}}
