import{events}from"./data.ts";
import{activeHoldStatuses,calculateTotal,canTransition,isExpired}from"./domain.ts";
import{reference,ticketPayload,token,verifyTicket}from"./security.ts";
import type{Audit,CheckInRecord,Order,Proof,Refund,TransferSettings}from"./types.ts";

type Notification={type:string;reference:string;recipient:string;createdAt:string;previewOnly:true};
type Store={orders:Map<string,Order>;proofs:Map<string,Proof>;checkIns:Map<string,CheckInRecord>;audit:Audit[];notifications:Notification[];settings:TransferSettings};
const globalStore=globalThis as unknown as{bazm?:Partial<Store>};
const defaults:TransferSettings={paymentMethod:"Bank transfer / mobile wallet",providerName:"Organiser details required",accountTitle:"BAZM — PLACEHOLDER",accountIdentifier:"•••• •••• •••• 2046",instructions:"Transfer the exact amount and include your booking reference where supported.",proofDeadlineMinutes:45,rejectionResubmitMinutes:30,supportContact:"@bazm.inn",receiptRetentionDays:90,placeholderActive:true,updatedAt:new Date().toISOString()};
const existing=globalStore.bazm;
export const store:Store={orders:existing?.orders??new Map(),proofs:existing?.proofs??new Map(),checkIns:existing?.checkIns??new Map(),audit:existing?.audit??[],notifications:existing?.notifications??[],settings:{...defaults,...existing?.settings}};
globalStore.bazm=store;

const audit=(action:string,actor:string,entity:string,reference?:string,note?:string)=>store.audit.unshift({id:token(10),action,actor,entity,reference,at:new Date().toISOString(),note});
const notify=(type:string,order:Order)=>store.notifications.unshift({type,reference:order.reference,recipient:order.email,createdAt:new Date().toISOString(),previewOnly:true});
function setStatus(order:Order,status:Order["status"]){if(!canTransition(order.status,status))throw Error(`Invalid order transition: ${order.status} → ${status}`);order.status=status}

export function expireStale(now=Date.now()){
  const expired:Order[]=[];
  for(const order of store.orders.values())if(["AWAITING_PAYMENT_PROOF","PAYMENT_REJECTED"].includes(order.status)&&isExpired(order.expiresAt,now)){setStatus(order,"EXPIRED");expired.push(order);audit("ORDER_EXPIRED","system","order",order.reference,"Inventory hold released");notify("BOOKING_EXPIRED",order)}
  return expired;
}
export function available(eventId:string,tierId:string,now=Date.now()){
  expireStale(now);const event=events.find(item=>item.id===eventId),tier=event?.tiers.find(item=>item.id===tierId);if(!tier)return 0;
  const held=[...store.orders.values()].filter(order=>order.eventId===eventId&&order.tierId===tierId&&activeHoldStatuses.includes(order.status)).reduce((sum,order)=>sum+order.quantity,0);
  return Math.max(0,tier.capacity-tier.sold-held);
}
export function createOrder(input:{eventId:string;tierId:string;quantity:number;fullName:string;email:string;phone:string},now=new Date()){
  const event=events.find(item=>item.id===input.eventId),tier=event?.tiers.find(item=>item.id===input.tierId);if(!event||!tier)throw Error("Event or ticket tier not found");if(event.status!=="UPCOMING")throw Error("This event is not bookable");if(!Number.isInteger(input.quantity)||input.quantity<1||input.quantity>tier.limit)throw Error(`Choose between 1 and ${tier.limit} tickets`);if(available(event.id,tier.id,+now)<input.quantity)throw Error("There are not enough tickets remaining");
  const ref=reference(),order:Order={id:token(),reference:ref,accessKey:token(24),eventId:event.id,tierId:tier.id,quantity:input.quantity,unitPrice:tier.price,fee:0,total:calculateTotal(tier.price,input.quantity),currency:"PKR",fullName:input.fullName.trim(),email:input.email.trim().toLowerCase(),phone:input.phone.trim(),status:"AWAITING_PAYMENT_PROOF",createdAt:now.toISOString(),expiresAt:new Date(+now+store.settings.proofDeadlineMinutes*60000).toISOString()};
  store.orders.set(ref,order);audit("ORDER_CREATED","customer","order",ref);notify("BOOKING_CREATED",order);return order;
}
export function customerOrder(ref:string,key?:string){expireStale();const order=store.orders.get(ref);return order&&order.accessKey===key?order:undefined}
export function staffOrder(ref:string){expireStale();return store.orders.get(ref)}
export function allOrders(){expireStale();return[...store.orders.values()].sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
export function searchOrders(query:string,status?:string){const needle=query.trim().toLowerCase();return allOrders().filter(order=>(!status||status==="ALL"||order.status===status)&&(!needle||[order.reference,order.fullName,order.email,order.phone,order.proof?.transaction||"",order.proof?.sender||""].some(value=>value.toLowerCase().includes(needle))))}
export function submitProof(ref:string,key:string,proof:Proof){const order=customerOrder(ref,key);if(!order)throw Error("Booking not found");if(isExpired(order.expiresAt))throw Error("The proof deadline has passed. Contact the organiser to reopen this booking.");if(!["AWAITING_PAYMENT_PROOF","PAYMENT_REJECTED"].includes(order.status))throw Error("This booking cannot accept payment proof");if(order.proof){store.proofs.delete(order.proof.id);audit("PROOF_SUPERSEDED","customer","payment_proof",ref,`Version ${order.proof.version}`)}order.proof=proof;order.submittedAt=proof.uploadedAt;setStatus(order,"PAYMENT_PROOF_SUBMITTED");order.customerReason=undefined;store.proofs.set(proof.id,proof);audit("PROOF_SUBMITTED","customer","payment_proof",ref,`Version ${proof.version}`);notify("PROOF_RECEIVED",order);return order}
export function beginReview(ref:string,actor="ADMIN"){const order=staffOrder(ref);if(!order)throw Error("Order not found");if(order.status==="UNDER_ORGANISER_REVIEW")return order;if(order.status!=="PAYMENT_PROOF_SUBMITTED")throw Error("Only submitted proof can enter review");setStatus(order,"UNDER_ORGANISER_REVIEW");order.reviewStartedAt=new Date().toISOString();audit("REVIEW_STARTED",actor,"payment_review",ref);return order}
export function review(ref:string,decision:"approve"|"reject",note:string,reason?:string,actor="ADMIN"){
  const order=staffOrder(ref);if(!order)throw Error("Order not found");if(decision==="approve"){if(order.status==="CONFIRMED")return order;if(!["PAYMENT_PROOF_SUBMITTED","UNDER_ORGANISER_REVIEW"].includes(order.status))throw Error("Only submitted proof can be approved");const event=events.find(item=>item.id===order.eventId),tier=event?.tiers.find(item=>item.id===order.tierId);if(!tier||tier.sold+order.quantity>tier.capacity)throw Error("Inventory can no longer be converted safely");tier.sold+=order.quantity;setStatus(order,"CONFIRMED");order.confirmedAt=new Date().toISOString();order.internalNote=note;order.tickets=Array.from({length:order.quantity},()=>ticketPayload(token(12),order.eventId));audit("INVENTORY_HOLD_CONVERTED",actor,"inventory",ref,`${order.quantity} tickets`);audit("PAYMENT_APPROVED",actor,"payment_review",ref,note);notify("PROOF_APPROVED",order)}else{if(order.status==="PAYMENT_REJECTED")return order;if(!["PAYMENT_PROOF_SUBMITTED","UNDER_ORGANISER_REVIEW"].includes(order.status))throw Error("Only submitted proof can be rejected");if(!reason?.trim())throw Error("A customer-facing reason is required");setStatus(order,"PAYMENT_REJECTED");order.internalNote=note;order.customerReason=reason;order.expiresAt=new Date(Date.now()+store.settings.rejectionResubmitMinutes*60000).toISOString();audit("PAYMENT_REJECTED",actor,"payment_review",ref,note);notify("PROOF_REJECTED",order)}return order;
}
export function reopen(ref:string,minutes:number,actor="ADMIN"){const order=staffOrder(ref);if(!order)throw Error("Order not found");if(order.status!=="EXPIRED")throw Error("Only expired bookings can be reopened");setStatus(order,"PAYMENT_REJECTED");order.expiresAt=new Date(Date.now()+minutes*60000).toISOString();order.customerReason="The organiser reopened this booking. Please submit valid proof before the new deadline.";audit("ORDER_REOPENED",actor,"order",ref,`${minutes} minutes`);return order}
export function recordRefund(ref:string,refund:Omit<Refund,"recordedAt"|"actor">,actor="ADMIN"){const order=staffOrder(ref);if(!order)throw Error("Order not found");if(order.status!=="CONFIRMED")throw Error("Only confirmed bookings can be marked refunded");if(refund.amount<0||refund.amount>order.total)throw Error("Refund amount is outside the order total");const event=events.find(item=>item.id===order.eventId),tier=event?.tiers.find(item=>item.id===order.tierId);if(tier)tier.sold=Math.max(0,tier.sold-order.quantity);setStatus(order,"REFUNDED");order.refund={...refund,recordedAt:new Date().toISOString(),actor};audit("REFUND_RECORDED",actor,"refund",ref,`${refund.amount} minor units · ${refund.reason} · no money moved by website`);notify("REFUND_RECORDED",order);return order}
export function updateSettings(input:TransferSettings,actor="ADMIN"){if(input.proofDeadlineMinutes<5||input.proofDeadlineMinutes>1440)throw Error("Proof deadline must be between 5 minutes and 24 hours");if(input.receiptRetentionDays<1||input.receiptRetentionDays>365)throw Error("Receipt retention must be between 1 and 365 days");store.settings={...input,updatedAt:new Date().toISOString()};audit("TRANSFER_SETTINGS_UPDATED",actor,"settings",undefined,input.placeholderActive?"Placeholder details active":"Production details marked active");return store.settings}
export function updateTier(eventId:string,tierId:string,input:{price:number;capacity:number;limit:number},actor="ADMIN"){const event=events.find(item=>item.id===eventId),tier=event?.tiers.find(item=>item.id===tierId);if(!event||!tier)throw Error("Tier not found");if(input.price<0||input.capacity<tier.sold||input.limit<1)throw Error("Invalid tier values");tier.price=Math.round(input.price);tier.capacity=Math.round(input.capacity);tier.limit=Math.round(input.limit);audit("TICKET_TIER_UPDATED",actor,"ticket_tier",undefined,`${event.title} · ${tier.name}`);return tier}
export function updateEventStatus(eventId:string,status:(typeof events)[number]["status"],actor="ADMIN"){const event=events.find(item=>item.id===eventId);if(!event)throw Error("Event not found");event.status=status;audit("EVENT_STATUS_UPDATED",actor,"event",undefined,`${event.title} · ${status}`);if(["CANCELLED","POSTPONED"].includes(status))for(const order of store.orders.values())if(order.eventId===eventId&&order.status==="CONFIRMED")notify(status==="CANCELLED"?"EVENT_CANCELLED":"EVENT_POSTPONED",order);return event}
export function purgeRetainedProofs(now=Date.now(),actor="system"){const cutoff=now-store.settings.receiptRetentionDays*86400000,removed:string[]=[];for(const order of store.orders.values()){if(order.proof&&Date.parse(order.proof.uploadedAt)<cutoff&&["EXPIRED","CANCELLED","REFUNDED"].includes(order.status)){store.proofs.delete(order.proof.id);removed.push(order.proof.storageKey);order.proof=undefined;audit("PAYMENT_PROOF_PURGED",actor,"payment_proof",order.reference)}}return removed}
export function checkIn(code:string,staff="DOOR_STAFF",expectedEventId?:string){const payload=verifyTicket(code);if(!payload)return{status:"INVALID"as const};const order=[...store.orders.values()].find(item=>item.tickets?.includes(code));if(!order||["CANCELLED","REFUNDED"].includes(order.status))return{status:"CANCELLED_OR_REFUNDED"as const};if(order.status!=="CONFIRMED")return{status:"INVALID"as const};if(expectedEventId&&order.eventId!==expectedEventId)return{status:"WRONG_EVENT"as const,order};const existing=store.checkIns.get(payload.tid);if(existing&&!existing.undoneAt)return{status:"ALREADY_USED"as const,order,record:existing};const record:CheckInRecord={ticketId:payload.tid,reference:order.reference,eventId:order.eventId,checkedAt:new Date().toISOString(),staff};store.checkIns.set(payload.tid,record);audit("CHECK_IN",staff,"check_in",order.reference);return{status:"VALID"as const,order,record}}
export function undoCheckIn(ticketId:string,reason:string,staff:string){const record=store.checkIns.get(ticketId);if(!record||record.undoneAt)throw Error("Active check-in not found");if(!reason.trim())throw Error("Undo reason is required");record.undoneAt=new Date().toISOString();record.undoReason=reason;audit("CHECK_IN_UNDONE",staff,"check_in",record.reference,reason);return record}

if(!store.orders.has("BZM-DEMO-1042")){const bytes=Uint8Array.from(Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=","base64"));const proof:Proof={id:"proof-demo",storageKey:"private/payment-proofs/demo.png",mime:"image/png",size:bytes.length,bytes,uploadedAt:new Date(Date.now()-900000).toISOString(),sender:"Demo customer",transaction:"TXN-DEMO-8821",transferAt:new Date(Date.now()-1500000).toISOString(),note:"Seeded review example",version:1,metadataStripped:false};store.proofs.set(proof.id,proof);store.orders.set("BZM-DEMO-1042",{id:"order-demo",reference:"BZM-DEMO-1042",accessKey:"demo-key",eventId:"river",tierId:"river-general",quantity:2,unitPrice:80000,fee:0,total:160000,currency:"PKR",fullName:"Demo Customer",email:"demo@example.test",phone:"+92 300 0000000",status:"PAYMENT_PROOF_SUBMITTED",createdAt:new Date(Date.now()-1800000).toISOString(),expiresAt:new Date(Date.now()+1800000).toISOString(),submittedAt:proof.uploadedAt,proof})}
