import{notFound}from"next/navigation";
import Nav from"@/components/Nav";
import Footer from"@/components/Footer";
import Deadline from"@/components/Deadline";
import{getCheckoutOrder}from"@/lib/ticketing";
import{getManagedEvent}from"@/lib/events";
import{store}from"@/lib/store";
import{dateTime,money}from"@/lib/format";
export const dynamic="force-dynamic";
export const metadata={title:"Booking status",robots:{index:false,follow:false}};
const copy:Record<string,[string,string]>={AWAITING_PAYMENT_PROOF:["Awaiting your transfer","Complete the transfer outside this website before the reservation expires."],EXPIRED:["Booking expired","The payment deadline passed and the reserved inventory has been released."],PAYMENT_PROOF_SUBMITTED:["Payment proof submitted","Payment review becomes operational in Stage 4."],UNDER_ORGANISER_REVIEW:["Under organiser review","Payment review becomes operational in Stage 4."],PAYMENT_REJECTED:["Payment proof needs attention","Contact Bazm for assistance."],CONFIRMED:["Booking confirmed","Your reservation has been confirmed."],CANCELLED:["Booking cancelled","This booking is closed."],REFUNDED:["Refund recorded","This booking is closed."]};
export default async function Page({params,searchParams}:{params:Promise<{reference:string}>;searchParams:Promise<{key?:string}>}){const{reference}=await params,{key}=await searchParams;if(!key)notFound();const order=await getCheckoutOrder(reference,key),event=order?await getManagedEvent(order.eventId):undefined;if(!order||!event)notFound();const[title,intro]=copy[order.status]||["Booking status","Contact Bazm for assistance."],settings=store.settings,active=order.status==="AWAITING_PAYMENT_PROOF",image=event.coverImageKey?`/api/event-images/${event.coverImageKey}`:"/assets/gallery.png";return<main><Nav/><header className="status-head paper"><div className="container"><p className="kicker">Booking {order.reference}</p><span className={`status ${order.status.toLowerCase()}`}>{order.status.replaceAll("_"," ")}</span><h1>{title}</h1><p>{intro}</p></div></header><section className="section"><div className="payment-layout"><div>{active?<><Deadline expiresAt={order.expiresAt} serverNow={new Date().toISOString()}/><div className="transfer"><header><span>Transfer instructions</span>{settings.placeholderActive&&<b>PLACEHOLDER DETAILS ACTIVE</b>}</header><dl><div><dt>Payment method</dt><dd>{settings.paymentMethod}</dd></div><div><dt>Bank / wallet</dt><dd>{settings.providerName}</dd></div><div><dt>Account title</dt><dd>{settings.accountTitle}</dd></div><div><dt>Account / IBAN / wallet</dt><dd>{settings.accountIdentifier}</dd></div><div><dt>Exact amount</dt><dd>{money(order.total)}</dd></div><div><dt>Booking reference</dt><dd>{order.reference}</dd></div><div><dt>Reservation deadline</dt><dd>{dateTime(order.expiresAt)} PKT</dd></div><div><dt>Support</dt><dd>{settings.supportContact}</dd></div></dl><p>{settings.instructions}</p></div><div className="notice"><b>Payment review arrives in Stage 4</b><p>Your tickets are reserved until the displayed deadline. Receipt upload and organiser approval are intentionally not enabled in this stage.</p></div></>:<div className="outcome"><i>×</i><h2>{title}</h2><p>{intro}</p><p><strong>Support:</strong> {settings.supportContact}</p></div>}</div><aside className="summary"><span>Booking status</span><img src={image} alt="Event artwork"/><h2>{order.eventTitle}</h2><p>{order.tierName} × {order.quantity}</p><dl><div><dt>Reference</dt><dd>{order.reference}</dd></div><div><dt>Tickets</dt><dd>{money(order.subtotal)}</dd></div><div><dt>Fees</dt><dd>{money(order.fee)}</dd></div><div><dt>Total</dt><dd>{money(order.total)}</dd></div><div><dt>Status</dt><dd>{order.status.replaceAll("_"," ")}</dd></div><div><dt>Deadline</dt><dd>{dateTime(order.expiresAt)} PKT</dd></div></dl></aside></div></section><Footer/></main>}
